/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2026-06-21 04:34:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.examen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import javax.persistence.*;
import org.openxava.jpa.XPersistence;
import ni.edu.uam.ProyectoFinalPOO.modelo.*;

public final class examen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.persistence");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("ni.edu.uam.ProyectoFinalPOO.modelo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.openxava.jpa.XPersistence");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("UTF-8");
    String pSesion = request.getParameter("sesion");
    String accion  = request.getParameter("accion");
    String clave   = request.getParameter("clave");

    Integer sesionId = null;
    if (pSesion != null && !pSesion.equals("null") && !pSesion.trim().isEmpty()) {
        try { sesionId = Integer.valueOf(pSesion.trim()); } catch (Exception e) {}
    }

    String error = null;
    String vista = "clave";              // clave | preguntas | resultado | error
    SesionTest sesion = null;
    List<Pregunta> preguntas = new ArrayList<Pregunta>();
    int aciertos = 0, total = 0;
    double porcentaje = 0;
    String observacion = "";

    if (sesionId == null) {
        error = "No se recibio una sesion valida. Abre el examen con el boton 'Iniciar test'.";
        vista = "error";
    } else {
        EntityManager em = XPersistence.getManager();
        sesion = em.find(SesionTest.class, sesionId);
        if (sesion == null) {
            error = "La sesion indicada no existe.";
            vista = "error";
        } else if ("validar".equals(accion) || "enviar".equals(accion)) {
            String claveReal = sesion.getClaveAcceso();
            if (claveReal == null || !claveReal.equals(clave)) {
                error = "Clave incorrecta.";
                vista = "clave";
            } else if ("enviar".equals(accion)) {
                preguntas = em.createQuery(
                                "from Pregunta p where p.forma = :f order by p.numero", Pregunta.class)
                        .setParameter("f", sesion.getForma()).getResultList();
                for (Pregunta p : preguntas) {
                    String marca = request.getParameter("p_" + p.getOid());
                    if (marca == null) marca = "";
                    boolean ok = p.getRespuestaCorrecta() != null
                            && p.getRespuestaCorrecta().equalsIgnoreCase(marca);
                    if (ok) aciertos++;
                    Respuesta r = new Respuesta();
                    r.setSesion(sesion);
                    r.setPregunta(p);
                    r.setValorMarcado(marca);
                    r.setCorrecta(ok);
                    em.persist(r);
                }
                total = preguntas.size();
                porcentaje = total > 0 ? Math.round(aciertos * 10000.0 / total) / 100.0 : 0;
                if (porcentaje >= 90) observacion = "Excelente";
                else if (porcentaje >= 70) observacion = "Satisfactorio";
                else if (porcentaje >= 60) observacion = "Aceptable";
                else observacion = "Necesita refuerzo";
                Resultado res = new Resultado();
                res.setSesion(sesion);
                res.setAciertos(aciertos);
                res.setTotalPreguntas(total);
                res.setPorcentaje(porcentaje);
                res.setObservacion(observacion);
                sesion.setEstado(EstadoSesion.CALIFICADA);
                em.persist(res);
                XPersistence.commit();
                vista = "resultado";
            } else {
                preguntas = em.createQuery(
                                "from Pregunta p where p.forma = :f order by p.numero", Pregunta.class)
                        .setParameter("f", sesion.getForma()).getResultList();
                vista = "preguntas";
            }
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Test Vocacional</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"examen.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"contenedor\">\r\n");
      out.write("    <h1>Test Vocacional</h1>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (error != null) { 
      out.write("\r\n");
      out.write("    <p style=\"color:#c00;font-weight:bold;\">");
      out.print( error );
      out.write("</p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if ("clave".equals(vista)) { 
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"examen.jsp\">\r\n");
      out.write("        <input type=\"hidden\" name=\"sesion\" value=\"");
      out.print( sesionId );
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"accion\" value=\"validar\">\r\n");
      out.write("        <p>Ingresa la clave de acceso para comenzar:</p>\r\n");
      out.write("        <input type=\"password\" name=\"clave\" required>\r\n");
      out.write("        <button type=\"submit\">Entrar</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    ");
 } else if ("preguntas".equals(vista)) { 
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"examen.jsp\">\r\n");
      out.write("        <input type=\"hidden\" name=\"sesion\" value=\"");
      out.print( sesionId );
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"accion\" value=\"enviar\">\r\n");
      out.write("        <input type=\"hidden\" name=\"clave\" value=\"");
      out.print( clave );
      out.write("\">\r\n");
      out.write("        <p>Forma ");
      out.print( sesion.getForma() );
      out.write(" — responde todas las preguntas:</p>\r\n");
      out.write("        ");
 for (Pregunta p : preguntas) { 
      out.write("\r\n");
      out.write("        <div class=\"pregunta\">\r\n");
      out.write("            <p><strong>");
      out.print( p.getNumero() );
      out.write(".</strong> ");
      out.print( p.getEnunciado() );
      out.write("</p>\r\n");
      out.write("            ");
 for (String op : new String[]{"A","B","C","D"}) { 
      out.write("\r\n");
      out.write("            <label style=\"margin-right:12px;\">\r\n");
      out.write("                <input type=\"radio\" name=\"p_");
      out.print( p.getOid() );
      out.write("\" value=\"");
      out.print( op );
      out.write("\" required> ");
      out.print( op );
      out.write("\r\n");
      out.write("            </label>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <button type=\"submit\">Enviar examen</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    ");
 } else if ("resultado".equals(vista)) { 
      out.write("\r\n");
      out.write("    <div class=\"resultado\">\r\n");
      out.write("        <h2>Resultado</h2>\r\n");
      out.write("        <p>Aciertos: <strong>");
      out.print( aciertos );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( total );
      out.write("</strong></p>\r\n");
      out.write("        <p>Porcentaje: <strong>");
      out.print( porcentaje );
      out.write("%</strong></p>\r\n");
      out.write("        <p>Observacion: <strong>");
      out.print( observacion );
      out.write("</strong></p>\r\n");
      out.write("        <p>Ya puedes cerrar esta ventana.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
